version: 2
jobs:
  build:
    docker:
      - image: circleci/build-image:ubuntu-14.04-XXL-upstart-1189-5614f37
    steps:
      - run:
          name: "Installing Linux and Checking Versions"
          command: |
            curl -L -o google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            sudo dpkg -i google-chrome.deb || true
            sudo apt-get update
            sudo apt-get install -f
            sudo apt-get install --only-upgrade lsb-base
            sudo dpkg -i google-chrome.deb
            google-chrome --version
      - run: npm test
      - store_test_results:
          path: /tmp/circleci-test-results
      - store_artifacts:
          path: /tmp/circleci-artifacts
      - store_artifacts:
          path: /tmp/circleci-test-results

