version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6.10
    environment:
      - CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      - CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
    steps:
      - checkout
      - run:
          name: Installing Google Chrome and Checking Versions
          command: |
            sudo apt-get install fonts-liberation libappindicator3-1
            curl -L -o google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            sudo dpkg -i google-chrome.deb || true
            sudo apt-get update
            sudo apt-get install -f
            sudo apt-get install --only-upgrade lsb-base
            sudo dpkg -i google-chrome.deb
            google-chrome --version
      - run: 
          name: Install dependencies
          command: npm install
      - run:
          name: Run unit tests
          command: npm test
      - store_test_results:
          path: /tmp/circleci-test-results
      - store_artifacts:
          path: /tmp/circleci-artifacts
      - store_artifacts:
          path: /tmp/circleci-test-results
