version: 2
jobs:
  build:
    docker:
      - image: node:8.0
    steps:
      - run:
          name: "Installing Linux and Checking Versions"
          command: |
            curl -L -o google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            dpkg -i google-chrome.deb || true
            apt-get update
            apt-get install -f
            apt-get install --only-upgrade lsb-base
            dpkg -i google-chrome.deb
            google-chrome --version

